=== nsomatrix/neutron/neutron/src/site/resources/2.0.2/device.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!-- @version $Revision$ ($Author$) $Date$ -->
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://www.neutron.org/2.0.2/" targetNamespace="http://www.neutron.org/2.0.2/" elementFormDefault="qualified" version="2.0.2">
	<xsd:annotation>
		<xsd:documentation>This is the XML Schema for the Neutron custom device descriptor.
			More information can be found here http://www.neutron.org/skin.html
		</xsd:documentation>
	</xsd:annotation>
	<xsd:element name="device" type="device">
		<xsd:annotation>
			<xsd:documentation>The device element is the root of the device descriptor.</xsd:documentation>
		</xsd:annotation>
	</xsd:element>
	<xsd:complexType name="device">
		<xsd:sequence>
			<xsd:element name="class-name" type="xsd:string" default="org.neutron.device.Device" minOccurs="0">
				<xsd:annotation>
					<xsd:documentation>The optional class that implements this device</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="system-properties" type="system-properties" minOccurs="0"/>
			<xsd:element name="img" type="img" minOccurs="0" maxOccurs="3">
				<xsd:annotation>
					<xsd:documentation>The image of the phone. Optional when device is extension.</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="display" type="display"/>
			<xsd:element name="fonts" type="fonts" minOccurs="0"/>
			<xsd:element name="input" type="input"/>
		</xsd:sequence>
		<xsd:attribute name="name" type="xsd:string" default="path">
			<xsd:annotation>
				<xsd:documentation>The name of this device</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
		<xsd:attribute name="extends" type="xsd:string">
			<xsd:annotation>
				<xsd:documentation>The path to parent device.xml for inheritance</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
	</xsd:complexType>
	<xsd:complexType name="system-properties">
		<xsd:annotation>
			<xsd:documentation>System properties. Ignored while running in applet. N.B. You can also add system-properties in config.cml</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name="system-property" minOccurs="0" maxOccurs="unbounded">
				<xsd:complexType>
					<xsd:attribute name="name" use="required"/>
					<xsd:attribute name="value"/>
				</xsd:complexType>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="img">
		<xsd:attribute name="name">
			<xsd:simpleType>
				<xsd:restriction base="xsd:string">
					<xsd:enumeration value="normal"/>
					<xsd:enumeration value="over"/>
					<xsd:enumeration value="pressed"/>
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
		<xsd:attribute name="src" type="xsd:string" default=""/>
	</xsd:complexType>
	<xsd:complexType name="display">
		<xsd:annotation>
			<xsd:documentation>Define device display capabilities</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name="iscolor" type="xsd:boolean" default="true" minOccurs="0">
				<xsd:annotation>
					<xsd:documentation>The screen is capable of displaying colors</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="numcolors" type="xsd:integer" minOccurs="0"/>
			<xsd:element name="numalphalevels" type="xsd:integer" minOccurs="0"/>
			<xsd:element name="foreground" type="xsd:string" default="000000" minOccurs="0">
				<xsd:annotation>
					<xsd:documentation>The foreground color of display</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="background" type="xsd:string" default="ffffff" minOccurs="0">
				<xsd:annotation>
					<xsd:documentation>The background color of display</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="rectangle" type="rectangle" minOccurs="0">
				<xsd:annotation>
					<xsd:documentation>The rectangle element gives the position and extent of the screen. Used by application when Canvas is set to full-screen mode.</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="paintable" type="paintable" minOccurs="0">
				<xsd:annotation>
					<xsd:documentation>The paintable element gives the position and extent of the area within the screen rectangle that a MIDlet paint on when Canvas is not set to full-screen mode (normal mode).</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="icon" type="icon" minOccurs="0" maxOccurs="unbounded">
				<xsd:annotation>
					<xsd:documentation>The input mode icons</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="status" type="status" minOccurs="0" maxOccurs="unbounded">
				<xsd:annotation>
					<xsd:documentation>The system status icons</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="paintable">
		<xsd:sequence>
			<xsd:element name="x" type="xsd:integer"/>
			<xsd:element name="y" type="xsd:integer"/>
			<xsd:element name="width" type="xsd:integer"/>
			<xsd:element name="height" type="xsd:integer"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="rectangle">
		<xsd:sequence>
			<xsd:element name="x" type="xsd:integer"/>
			<xsd:element name="y" type="xsd:integer"/>
			<xsd:element name="width" type="xsd:integer"/>
			<xsd:element name="height" type="xsd:integer"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="polygon">
		<xsd:sequence>
			<xsd:element name="point" type="point" minOccurs="3" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="point">
		<xsd:attribute name="x" type="xsd:integer" use="required"/>
		<xsd:attribute name="y" type="xsd:integer" use="required"/>
	</xsd:complexType>
	<xsd:complexType name="icon">
		<xsd:sequence>
			<xsd:element name="paintable" type="paintable"/>
			<xsd:element name="img" type="img" maxOccurs="unbounded"/>
		</xsd:sequence>
		<xsd:attribute name="name" type="xsd:string"/>
	</xsd:complexType>
	<xsd:complexType name="status">
		<xsd:sequence>
			<xsd:element name="paintable" type="paintable"/>
			<xsd:element name="img" type="statusImg" maxOccurs="unbounded"/>
		</xsd:sequence>
		<xsd:attribute name="name" type="xsd:string"/>
	</xsd:complexType>
	<xsd:complexType name="statusImg">
		<xsd:attribute name="name" type="xsd:string"/>
		<xsd:attribute name="src" type="xsd:string"/>
	</xsd:complexType>
	<xsd:complexType name="fonts">
		<xsd:sequence>
			<xsd:element name="font" type="fontMapping" maxOccurs="unbounded"/>
		</xsd:sequence>
		<xsd:attribute name="hint" type="xsd:string"/>
	</xsd:complexType>
	<xsd:complexType name="fontMapping">
		<xsd:annotation>
			<xsd:documentation>Mapping to system fonts</xsd:documentation>
		</xsd:annotation>
		<xsd:complexContent>
			<xsd:extension base="fontBase">
				<xsd:choice>
					<xsd:element name="system" type="system"/>
					<xsd:element name="ttf" type="ttf"/>
				</xsd:choice>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>
	<xsd:complexType name="fontReference">
		<xsd:complexContent>
			<xsd:extension base="fontBase"/>
		</xsd:complexContent>
	</xsd:complexType>
	<xsd:complexType name="fontBase" abstract="true">
		<xsd:annotation>
			<xsd:documentation>j2me system fonts</xsd:documentation>
		</xsd:annotation>
		<xsd:attribute name="face">
			<xsd:annotation>
				<xsd:documentation>Font face as in lcdui API javax.microedition.lcdui.Font Font.FACE_SYSTEM, Font.FACE_MONOSPACE, or Font.FACE_PROPORTIONAL</xsd:documentation>
			</xsd:annotation>
			<xsd:simpleType>
				<xsd:restriction base="xsd:string">
					<xsd:enumeration value="FACE_MONOSPACE"/>
					<xsd:enumeration value="FACE_PROPORTIONAL"/>
					<xsd:enumeration value="FACE_SYSTEM"/>
					<xsd:enumeration value="monospace"/>
					<xsd:enumeration value="proportional"/>
					<xsd:enumeration value="system"/>
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
		<xsd:attribute name="style">
			<xsd:annotation>
				<xsd:documentation>Font style bold, italic or plain. Comma separated list</xsd:documentation>
			</xsd:annotation>
			<xsd:simpleType>
				<xsd:restriction base="xsd:string">
					<xsd:enumeration value="STYLE_PLAIN"/>
					<xsd:enumeration value="STYLE_BOLD"/>
					<xsd:enumeration value="STYLE_ITALIC"/>
					<xsd:enumeration value="STYLE_BOLD,STYLE_ITALIC"/>
					<xsd:enumeration value="plain"/>
					<xsd:enumeration value="bold"/>
					<xsd:enumeration value="italic"/>
					<xsd:enumeration value="bold,italic"/>
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
		<xsd:attribute name="size">
			<xsd:simpleType>
				<xsd:restriction base="xsd:string">
					<xsd:enumeration value="SIZE_LARGE"/>
					<xsd:enumeration value="SIZE_MEDIUM"/>
					<xsd:enumeration value="SIZE_SMALL"/>
					<xsd:enumeration value="large"/>
					<xsd:enumeration value="medium"/>
					<xsd:enumeration value="small"/>
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
	</xsd:complexType>
	<xsd:complexType name="system">
		<xsd:annotation>
			<xsd:documentation>Describe system font that used for display</xsd:documentation>
		</xsd:annotation>
		<xsd:attribute name="name" type="xsd:string"/>
		<xsd:attribute name="style" type="xsd:string">
			<xsd:annotation>
				<xsd:documentation>Font style bold, italic or plain. Comma separatedlist</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
		<xsd:attribute name="size" type="xsd:integer"/>
	</xsd:complexType>
	<xsd:complexType name="ttf">
		<xsd:annotation>
			<xsd:documentation>Describe true type font used for display</xsd:documentation>
		</xsd:annotation>
		<xsd:attribute name="src" type="xsd:string"/>
		<xsd:attribute name="style" type="xsd:string">
			<xsd:annotation>
				<xsd:documentation>Font style bold, italic or plain. Comma separatedlist</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
		<xsd:attribute name="size" type="xsd:integer"/>
	</xsd:complexType>
	<xsd:complexType name="input">
		<xsd:sequence>
			<xsd:element name="haspointerevents" type="xsd:boolean" default="false" minOccurs="0">
				<xsd:annotation>
					<xsd:documentation>The platform supports pointer press and release events</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="haspointermotionevents" type="xsd:boolean" default="false" minOccurs="0">
				<xsd:annotation>
					<xsd:documentation>The platform supports pointer motion events</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="hasrepeatevents" type="xsd:boolean" default="false" minOccurs="0">
				<xsd:annotation>
					<xsd:documentation>The platform can generate repeat events when key is kept down</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="softbutton" type="softbutton" minOccurs="0" maxOccurs="unbounded"/>
			<xsd:element name="button" type="button" minOccurs="0" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="chars">
		<xsd:sequence>
			<xsd:element name="char" type="xsd:string" maxOccurs="unbounded"/>
		</xsd:sequence>
		<xsd:attribute name="input" type="xsd:string"/>
	</xsd:complexType>
	<xsd:complexType name="button">
		<xsd:annotation>
			<xsd:documentation/>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name="chars" type="chars" minOccurs="0" maxOccurs="unbounded"/>
			<xsd:choice>
				<xsd:element name="rectangle" type="rectangle"/>
				<xsd:element name="polygon" type="polygon"/>
			</xsd:choice>
		</xsd:sequence>
		<xsd:attribute name="name" type="xsd:string" use="required">
			<xsd:annotation>
				<xsd:documentation>Name of the button. e.g. 0, 1, 2 ... # *</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
		<xsd:attribute name="key" type="xsd:string">
			<xsd:annotation>
				<xsd:documentation>Computer keyboard key codes space separated used to trigger this button.</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
		<xsd:attribute name="keyboardChars" type="xsd:string">
			<xsd:annotation>
				<xsd:documentation>Computer keyboard key codes in character (not separated) used to trigger this button.</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
		<xsd:attribute name="keyCode" type="xsd:string">
			<xsd:annotation>
				<xsd:documentation>Keyboard key code passed to Canvas.keyPressed() finction</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
		<xsd:attribute name="modeChange" type="xsd:boolean">
			<xsd:annotation>
				<xsd:documentation>This button is modeChange button for text inputs</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
	</xsd:complexType>
	<xsd:complexType name="softbutton">
		<xsd:annotation>
			<xsd:documentation/>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:choice>
				<xsd:element name="rectangle" type="rectangle"/>
				<xsd:element name="polygon" type="polygon"/>
			</xsd:choice>
			<xsd:element name="paintable" type="paintable"/>
			<xsd:element name="font" type="fontReference" minOccurs="0"/>
			<xsd:element name="command" type="command" maxOccurs="unbounded">
				<xsd:annotation>
					<xsd:documentation>As defined in javax.microedition.lcdui.Command</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
		</xsd:sequence>
		<xsd:attribute name="name" type="xsd:string" use="required">
			<xsd:annotation>
				<xsd:documentation>Name of the button. Identify the button function e.g. SOFT1, SOFT2</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
		<xsd:attribute name="key" type="xsd:string">
			<xsd:annotation>
				<xsd:documentation>Computer keyboard key code used to trigger this button.</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
		<xsd:attribute name="keyCode" type="xsd:string">
			<xsd:annotation>
				<xsd:documentation>Keyboard key code passed to Canvas.keyPressed() finction</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
		<xsd:attribute name="alignment">
			<xsd:simpleType>
				<xsd:restriction base="xsd:string">
					<xsd:enumeration value="LEFT"/>
					<xsd:enumeration value="RIGHT"/>
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
	</xsd:complexType>
	<xsd:simpleType name="command">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="BACK"/>
			<xsd:enumeration value="CANCEL"/>
			<xsd:enumeration value="EXIT"/>
			<xsd:enumeration value="HELP"/>
			<xsd:enumeration value="ITEM"/>
			<xsd:enumeration value="OK"/>
			<xsd:enumeration value="SCREEN"/>
			<xsd:enumeration value="STOP"/>
		</xsd:restriction>
	</xsd:simpleType>
</xsd:schema>

=== nsomatrix/neutron/neutron/neutron-extensions/neutron-device-minimum/build/resources/main/org/neutron/device/minimum/device.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<device name="Minimum device" xmlns="http://www.neutron.org/2.0.2/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.neutron.org/2.0.2/ http://www.neutron.org/2.0.2/device.xsd">
<!-- @version $Id$ -->
	<img name="normal" src="normal.png"/>
	<img name="over" src="over.png"/>
	<img name="pressed" src="pressed.png"/>
	<display>
		<iscolor>false</iscolor>
		<numcolors>4</numcolors>
		<numalphalevels>2</numalphalevels>
		<foreground>000000</foreground>
		<background>c3cbb6</background>
		<rectangle>
			<x>15</x>
			<y>17</y>
			<width>128</width>
			<height>128</height>
		</rectangle>
		<paintable>
			<x>0</x>
			<y>10</y>
			<width>128</width>
			<height>96</height>
		</paintable>
		<icon name="up">
			<paintable>
				<x>60</x>
				<y>112</y>
				<width>8</width>
				<height>8</height>
			</paintable>
			<img name="normal" src="up.png"/>
		</icon>
		<icon name="down">
			<paintable>
				<x>60</x>
				<y>120</y>
				<width>8</width>
				<height>8</height>
			</paintable>
			<img name="normal" src="down.png"/>
		</icon>
		<status name="input">
			<paintable>
				<x>1</x>
				<y>1</y>
				<width>14</width>
				<height>7</height>
			</paintable>
			<img name="123" src="/org/neutron/device/default/123.png"/>
			<img name="ABC" src="/org/neutron/device/default/abc_upper.png"/>
			<img name="abc" src="/org/neutron/device/default/abc_lower.png"/>
		</status>
	</display>
	<input>
		<softbutton name="SOFT1" alignment="LEFT">
			<polygon>
				<point x="21" y="153" />
				<point x="62" y="153" />
				<point x="51" y="161" />
				<point x="51" y="169" />
				<point x="60" y="176" />
				<point x="21" y="176" />
			</polygon>
			<paintable>
				<x>0</x>
				<y>112</y>
				<!-- (128 - 8)/2 -->
				<width>60</width>
				<height>16</height>
			</paintable>
			<command>BACK</command>
			<command>EXIT</command>
			<command>CANCEL</command>
			<command>STOP</command>
		</softbutton>
		<softbutton name="SOFT2" alignment="RIGHT">
			<polygon>
				<point x="96" y="153" />
				<point x="138" y="153" />
				<point x="138" y="177" />
				<point x="96" y="177" />
				<point x="107" y="169" />
				<point x="107" y="162" />
			</polygon>
			<paintable>
				<x>68</x>
				<y>112</y>
				<width>60</width>
				<height>16</height>
			</paintable>
			<command>OK</command>
			<command>SCREEN</command>
			<command>ITEM</command>
			<command>HELP</command>
		</softbutton>
		<button name="LEFT">
			<polygon>
				<point x="53" y="161" />
				<point x="59" y="156" />
				<point x="64" y="155" />
				<point x="64" y="177" />
				<point x="57" y="173" />
				<point x="53" y="169" />
			</polygon>
		</button>
		<button name="RIGHT">
			<polygon>
				<point x="93" y="153" />
				<point x="102" y="158" />
				<point x="106" y="163" />
				<point x="106" y="168" />
				<point x="102" y="174" />
				<point x="93" y="178" />
			</polygon>
		</button>
		<button name="UP">
			<rectangle>
				<x>60</x>
				<y>149</y>
				<width>34</width>
				<height>10</height>
			</rectangle>
		</button>
		<button name="DOWN">
			<rectangle>
				<x>61</x>
				<y>173</y>
				<width>37</width>
				<height>12</height>
			</rectangle>
		</button>
		<button name="SELECT">
			<rectangle>
				<x>68</x>
				<y>159</y>
				<width>22</width>
				<height>14</height>
			</rectangle>
		</button>
		<button name="0">
			<chars>
				<char> </char>
				<char>0</char>
			</chars>
			<rectangle>
				<x>59</x>
				<y>257</y>
				<width>40</width>
				<height>22</height>
			</rectangle>
		</button>
		<button name="1">
			<chars>
				<char>.</char>
				<char>,</char>
				<char>?</char>
				<char>!</char>
				<char>:</char>
				<char>;</char>
				<char>-</char>
				<char>+</char>
				<char>#</char>
				<char>*</char>
				<char>(</char>
				<char>)</char>
				<char>'</char>
				<char>"</char>
				<char>_</char>
				<char>@</char>
				<char>&amp;</char>
				<char>$</char>
				<char>%</char>
				<char>/</char>
				<char>&lt;</char>
				<char>&gt;</char>
				<char>=</char>
				<char>1</char>
			</chars>
			<chars input="123">
				<char>1</char>
				<char>.</char>
				<char>-</char>
				<char>(</char>
				<char>)</char>
				<char>+</char>
			</chars>
			<rectangle>
				<x>10</x>
				<y>182</y>
				<width>41</width>
				<height>24</height>
			</rectangle>
		</button>
		<button name="2">
			<chars>
				<char>a</char>
				<char>b</char>
				<char>c</char>
				<char>2</char>
			</chars>
			<rectangle>
				<x>60</x>
				<y>186</y>
				<width>41</width>
				<height>24</height>
			</rectangle>
		</button>
		<button name="3">
			<chars>
				<char>d</char>
				<char>e</char>
				<char>f</char>
				<char>3</char>
			</chars>
			<rectangle>
				<x>109</x>
				<y>183</y>
				<width>41</width>
				<height>24</height>
			</rectangle>
		</button>
		<button name="4">
			<chars>
				<char>g</char>
				<char>h</char>
				<char>i</char>
				<char>4</char>
			</chars>
			<rectangle>
				<x>10</x>
				<y>207</y>
				<width>41</width>
				<height>24</height>
			</rectangle>
		</button>
		<button name="5">
			<chars>
				<char>j</char>
				<char>k</char>
				<char>l</char>
				<char>5</char>
			</chars>
			<rectangle>
				<x>59</x>
				<y>209</y>
				<width>41</width>
				<height>23</height>
			</rectangle>
		</button>
		<button name="6">
			<chars>
				<char>m</char>
				<char>n</char>
				<char>o</char>
				<char>6</char>
			</chars>
			<rectangle>
				<x>109</x>
				<y>206</y>
				<width>41</width>
				<height>23</height>
			</rectangle>
		</button>
		<button name="7">
			<chars>
				<char>p</char>
				<char>q</char>
				<char>r</char>
				<char>s</char>
				<char>7</char>
			</chars>
			<rectangle>
				<x>10</x>
				<y>231</y>
				<width>41</width>
				<height>23</height>
			</rectangle>
		</button>
		<button name="8">
			<chars>
				<char>t</char>
				<char>u</char>
				<char>v</char>
				<char>8</char>
			</chars>
			<rectangle>
				<x>59</x>
				<y>233</y>
				<width>41</width>
				<height>23</height>
			</rectangle>
		</button>
		<button name="9">
			<chars>
				<char>w</char>
				<char>x</char>
				<char>y</char>
				<char>z</char>
				<char>9</char>
			</chars>
			<rectangle>
				<x>109</x>
				<y>230</y>
				<width>41</width>
				<height>23</height>
			</rectangle>
		</button>
		<button name="ASTERISK">
			<chars>
				<char>*</char>
				<char>+</char>
			</chars>
			<rectangle>
				<x>10</x>
				<y>254</y>
				<width>41</width>
				<height>23</height>
			</rectangle>
		</button>
		<button name="POUND" modeChange="true">
			<rectangle>
				<x>109</x>
				<y>254</y>
				<width>41</width>
				<height>23</height>
			</rectangle>
		</button>
	</input>
</device>

=== nsomatrix/neutron/neutron/neutron-extensions/neutron-device-resizable/src/main/resources/org/neutron/device/resizable/device-ru.xml
<?xml version="1.0" encoding="UTF-8"?>
<device	name="Resizable device - russian keyboard"
	    extends= "device.xml"
	    xmlns="http://www.neutron.org/2.0.2/"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://www.neutron.org/2.0.2/ http://www.neutron.org/2.0.2/device.xsd">
    <input>
        <button name="2">
            <chars override="true">
                <char>a</char>
                <char>b</char>
                <char>c</char>
				<char>&#1072;</char>
				<char>&#1073;</char>
				<char>&#1074;</char>
				<char>&#1075;</char>
                <char>2</char>
            </chars>
        </button>
        <button name="3">
            <chars override="true">
                <char>d</char>
                <char>e</char>
                <char>f</char>
				<char>&#1076;</char>
				<char>&#1077;</char>
				<char>&#1105;</char>
				<char>&#1078;</char>
				<char>&#1079;</char>
                <char>3</char>
            </chars>
        </button>
        <button name="4">
            <chars override="true">
                <char>g</char>
                <char>h</char>
                <char>i</char>
				<char>&#1080;</char>
				<char>&#1081;</char>
				<char>&#1082;</char>
				<char>&#1083;</char>
                <char>4</char>
            </chars>
        </button>
        <button name="5">
            <chars override="true">
                <char>j</char>
                <char>k</char>
                <char>l</char>
				<char>&#1084;</char>
				<char>&#1085;</char>
				<char>&#1086;</char>
				<char>&#1087;</char>
                <char>5</char>
            </chars>
        </button>
        <button name="6">
            <chars override="true">
                <char>m</char>
                <char>n</char>
                <char>o</char>
				<char>&#1088;</char>
				<char>&#1089;</char>
				<char>&#1090;</char>
				<char>&#1091;</char>
                <char>6</char>
            </chars>
        </button>
        <button name="7">
            <chars override="true">
                <char>p</char>
                <char>q</char>
                <char>r</char>
                <char>s</char>
				<char>&#1092;</char>
				<char>&#1093;</char>
				<char>&#1094;</char>
				<char>&#1095;</char>
                <char>7</char>
            </chars>
        </button>
        <button name="8">
            <chars override="true">
                <char>t</char>
                <char>u</char>
                <char>v</char>
				<char>&#1096;</char>
				<char>&#1097;</char>
				<char>&#1098;</char>
				<char>&#1099;</char>
                <char>8</char>
            </chars>
        </button>
        <button name="9">
            <chars override="true">
                <char>w</char>
                <char>x</char>
                <char>y</char>
                <char>z</char>
				<char>&#1100;</char>
				<char>&#1101;</char>
				<char>&#1102;</char>
				<char>&#1103;</char>
                <char>9</char>
            </chars>
        </button>
    </input>
</device>

=== nsomatrix/neutron/neutron/neutron-extensions/neutron-device-minimum/src/main/resources/org/neutron/device/minimum/device-color.xml
<?xml version="1.0"	encoding="ISO-8859-1"?>
<device	name="Minimum device color"
	extends= "device.xml"
	xmlns="http://www.neutron.org/2.0/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.neutron.org/2.0/	http://www.neutron.org/2.0/device.xsd">
	<display>
		<iscolor>true</iscolor>
		<numcolors>65536</numcolors>
		<numalphalevels>256</numalphalevels>
		<foreground>000000</foreground>
		<background>ffffff</background>
		<icon name="up">
			<img name="pressed" src="up.png"/>
		</icon>
		<icon name="down">
			<img name="pressed" src="down.png"/>
		</icon>
	</display>
	<input>
		<haspointerevents>true</haspointerevents>
		<haspointermotionevents>true</haspointermotionevents>
		<hasrepeatevents>true</hasrepeatevents>
	</input>
</device>
